### ISSUE TITLE
Global environment pollution in boot.lua

### ISSUE THREAD

**Issue by agladysh** [love2d/love-old#1]
```
diff --git a/src/scripts/boot.lua b/src/scripts/boot.lua
index b7d7338..87bb87c 100644
--- a/src/scripts/boot.lua
+++ b/src/scripts/boot.lua
@@ -817,7 +817,7 @@ function love.errhand(msg)
        draw()

        while true do
-               e, a, b, c = love.event.wait()
+               local e, a, b, c = love.event.wait()

                if e == "q" then
                        return
```

**Comment by bartbes** [comment]
Thanks for the report, I fixed it (though it might take some time before it shows in this mirror).
I would like to add that it isn't that bad anyway, since the error handler is not really meant to return anyway.

**Comment by agladysh** [comment]
Thanks. It triggered the run-time global environment protection that I use — that's why I've reported this.
