### ISSUE TITLE
Guidelines to build love2d on OS X

### ISSUE THREAD

**Issue by agladysh** [love2d/love-old#2]
Are there any guidelines on how to build love2d on OS X? Where to get all those frameworks?

**Comment by love2d** [comment]
You can download the frameworks here: http://dl.dropbox.com/u/1830330/Frameworks.zip

Just place the contents of the zip archive in /Library/Frameworks.

**Comment by agladysh** [comment]
Thanks. OpenAL.framework is still missing for me (OS X 10.6.3, XCode 3.3.2)

**Comment by love2d** [comment]
Odd. OpenAL.framework should be in /System/Library/Frameworks - it's a core part of Mac OS X. I definitely have it, and I'm running 10.6.3 as well.

**Comment by agladysh** [comment]
After more investigation, I've found that, indeed, I do have OpenAL.framework on my machine, but it is displayed as not found in project.

It seems that path to the framework in the project file is botched. Deleting framework and adding it back fixed the problem.

Old configuration:

```
path = System/Library/Frameworks/OpenAL.framework; 
sourceTree = SDKROOT;
```

New configuration:

```
path = /System/Library/Frameworks/OpenAL.framework; 
sourceTree = "<absolute>";
```

**Comment by algorev** [comment]
Does this count as closed?
