### ISSUE TITLE
Generating *.lua.h

### ISSUE THREAD

**Issue by agladysh** [love2d/love-old#3]
I've changed some src/scripts/*.lua files and want to generate *.lua.h for them.
OS X build does not seem to update these files automatically.

How should I generate them?

**Comment by love2d** [comment]
In src/scripts, there should be a file "auto.lua". From the command line, cd into src/scripts and run the following:

```
lua auto.lua boot graphics audio
```

You can leave out any of the files you haven't modified. But that's how to generate the .h files.

**Comment by agladysh** [comment]
Thanks, that helped.
