### ISSUE TITLE
More global namespace pollution by boot.lua

### ISSUE THREAD

**Issue by agladysh** [love2d/love-old#4]
Below is a list of variable names along with line numbers where they are being get or set. I think at least that some of them are bugs (e.g. that "parent" one). 

But even for legitimate ones, can't they be replaced with upvalues? It is more clean, and, also, would not conflict with the run-time global environment protection I use.

```
Belt    540,541,541,542,544,565,569,595,610
Bubble  634,635,635,636,638,643,647,651,686
Knoll   523,524,524,525,527,702,712
List    396,397,397,399,403,407,415,430,681,682
Node    423,424,424,426,434,440,444,446
Object  444,445,445,446,448,462,466,474,485,487,502,504,523,525,540,542,601,603,634,636
Star    502,503,503,504,506,519,536,707
Tank    601,602,602,603,605,614,618,624,691
Timer   659,660,660,662,668,672
Tree    485,486,486,487,489,498,696
arg 122,133,137,191,299
argv    29
images  379,382,387,388,391,392,491,508,597,625,626,627,628,629,630,653,654
lists   683,687,692,697,703,708,713,716,729,739,748
major   343,344,344,628
minor   343,345,345,629
names   373,381
no_game_code    205,286
parent  441
pools   394,529,529
result  840,841,842,843,844,845
rev 343,346,346,630
timers  657,669,726
```

You may generate this list as follows:

```
luac -l -l -o /dev/null boot.lua | grep ETGLOBAL \
  | egrep -v 'string|table|xpcall|tostring|love|pairs|math|print|require|pcall|assert|debug|error' \
  | awk '{print $7 "\t" $2;}' | sed -e 's/\]//g' | sed -e 's/\[//g' \
  | sort -n | awk '
     BEGIN { }
     !A[$1] {A[$1] = $0; next}
     {A[$1] = A[$1] "," $2}
     END {for(i in A) {print A[i]}
  }' | sort
```

**Comment by agladysh** [comment]
Any comments?
I may try to produce a patch myself...

**Comment by bartbes** [comment]
I just fixed the 1 bug of those that is in there, and that is result, all of the others are either intended (and can't be upvalues) or set when there is no user code to run. It might take a while before you see it though, it seems the mirroring script stopped mirroring.

**Comment by agladysh** [comment]
Thanks.

But can't "intended" globals be put into some namespace at least?

**Comment by bartbes** [comment]
Most of them will be removed next version anyway (as they are for the no game screen, and we create a new one every major version), I won't fix this anytime sooner though.

**Comment by algorev** [comment]
Closed?
