### ISSUE TITLE
Windows love.exe is not DPI-aware

### ISSUE THREAD

**Issue by BujuArena** [love2d/love-old#85]
A friend ran our pixel-art game on his computer where he has high DPI scaling settings in Windows and he pointed out that love.exe is not DPI-aware, so our game was upscaled on his Windows machine in an undesirable way we did not design.  We are planning to use love.window.getPixelScale and love.window.setMode to set the correct scaling, but Windows users with high DPI displays will not see our accurate scaling.

"dpiAware" is a setting in the application manifest attached to the exe (effectively should just be called "exe settings", as it tells Windows how to run the program).  Here are two MSDN articles explaining "Application Manifests" and the position of the "dpiAware" setting.

https://msdn.microsoft.com/en-us/library/aa375635(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/aa374191(v=vs.85).aspx

Until this is changed in the official releases, I will be editing the manifest in my copy of love.exe to enable "dpiAware", then linking the .love game file to the edited love.exe for distribution.

**Comment by BujuArena** [comment]
Why was this closed?  As far as I know, it was not resolved.

**Comment by slime73** [comment]
This is the wrong repository for issue reporting. As you can see, the latest commit here was 10 years ago.

Historically issues have been on our main bitbucket repository. https://bitbucket.org/rude/love/issues/1416/per-monitor-dpi-scale-for-windows

However we're about to move all of those to the new github repository at https://github.com/love2d/love (which is not this repository).

**Comment by BujuArena** [comment]
Okay.  Thanks for maintaining this project and for moving this one over.  It still affects Windows games for anyone with high-DPI displays, afaik.

By the way, there is a checkbox for "Issues" in github project settings if you want to disable the "Issues" tab for this project.  That would help protect bug reports from being lost like this one in the future.

**Comment by slime73** [comment]
When you first posted this issue, we didn't have control of this repository. I'm going to archive this repo (I already tried earlier today actually, but there was some internal error in github)
