### ISSUE TITLE
On macOS, the title bar is dark-grey

### ISSUE THREAD

**Issue by zac-garby** [love2d/love-old#86]
<img width="471" alt="screen shot 2016-11-16 at 16 23 15" src="https://cloud.githubusercontent.com/assets/19708658/20355360/03389c70-ac19-11e6-97bb-cfc6242956a6.png">

As you can see in the picture, the title bar is dark grey instead of light grey.

**Comment by algorev** [comment]
It is related to the way cocoa handles title bar colours. The title bar is coloured after the background colour (which seems to be black by default in our case) and changing this would require editing the source of the SDL, which would probably not be worth all the trouble, as most games would probably be fullscreen anyway, on one platform. I don't think this is worth forking the SDL, maintaining a separate copy and all the rest just for that. Explanation: https://discourse.libsdl.org/t/question-about-title-bar-color-on-osx/23275/2

This probably won't be fixed, as 2.0.8 is the current version.

**Comment by slime73** [comment]
This has been fixed in recent versions of love.
