### ISSUE TITLE
please add back in love.window.getWidth and love.window.getHeight for quick access 

### ISSUE THREAD

**Issue by Shadowblitz16** [love2d/love-old#89]
please add back in love.window.getWidth and love.window.getHeight for quick access.
I feel the user shouldn't have to assign a variable to love.window.getMode first before using this.

**Comment by justinmchase** [comment]
Just do this:
```
w, h = love.graphics.getDimensions( )
```

**Comment by rm-code** [comment]
@Shadowblitz16 `love.window.getWidth` was replaced by `love.graphics.getWidth` in 0.10.0.

**Comment by Shadowblitz16** [comment]
thankyou @rm-code
